---
title: Lance Gutin
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  travel:
    title: Travel
    output: true
  uploads:
    title: Uploads
    output: true
  design:
    title: Design
    output: true
  writing:
    title: Writing
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: writing
  values:
    layout: article
    permalink: "/design/writing/:path"
- scope:
    path: ''
    type: travel
  values:
    layout: article
- scope:
    path: ''
    type: design
  values:
    layout: default
permalink: pretty
markdown: kramdown
analytics_id: UA-17044912-3
description: Designer
plugins:
  - jekyll-redirect-from